version: 2.1 
orbs:
  node: circleci/node@4.7.0 
jobs:
  build:
    working directory: ~/Software_Engineering/src
    docker:
      - image: cimg/node:Its 
    steps:
      - checkout:
          path: ~/Software_Engineering
      - run: npm install